name: Weekly ECDC CDTR Mailer

on:
  # ✅ Ejecución automática semanal (miércoles 09:00 UTC)
  schedule:
    - cron: "0 9 * * 3"
  # ✅ Botón para lanzarlo manualmente cuando quieras
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: weekly-ecdc-cdtr
  cancel-in-progress: false

jobs:
  run-agent:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          else
            # Por si no hay requirements.txt, instala mínimos
            pip install requests beautifulsoup4
          fi

      - name: Run weekly agent
        env:
          LOG_LEVEL: INFO
          SMTP_SERVER: ${{ secrets.SMTP_SERVER }}
          SMTP_PORT: ${{ secrets.SMTP_PORT }}
          SENDER_EMAIL: ${{ secrets.SENDER_EMAIL }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
          RECEIVER_EMAIL: ${{ secrets.RECEIVER_EMAIL }}
          # DRY_RUN: "1"   # ← déjalo comentado; úsalo si quieres probar sin enviar
        run: |
          python weekly_agent.py
